openapi: 3.0.0
info:
  title: MyLife GPT Webhook Receiver API
  description: |
    This API is for receiving webhooks from [MyLife's public Biographer Bot instance](https://chat.openai.com/g/g-QGzfgKj6I-mylife-biographer-bot).
    ## Updates
    - added: keywords, phaseOfLife, relationships to bot package
  version: 1.0.1
servers:
  - url: https://humanremembranceproject.org/api/v1
    description: Endpoint for receiving stories from the MyLife Biographer Bot instance.
security:
  - bearerAuth: []
paths:
  /keyValidation/{mid}:
    post:
      x-openai-isConsequential: false
      operationId: MyLifeKeyValidation
      summary: MyLife Biographer Bot will access this endpoint to validate a `memberKey` in MyLife Cosmos.
      description: Endpoint for handling incoming registration webhook data from the MyLife GPT service.
      parameters:
        - name: mid
          in: path
          required: true
          description: The `memberKey` data to be sent by MyLife Biographer Bot. Visitor enters memberKey and it is kept in GPT memory and sent with each request so that MyLife knows partition.
          schema:
            maxLength: 256
            minLength: 40
            type: string
      responses:
        "200":
          description: A successful response indicating the member key is valid
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Valid member.
                  data:
                    type: object
                    properties:
                      mbr_id:
                        maxLength: 256
                        minLength: 40
                        type: string
                      updates:
                        type: string
                      interests:
                        type: string
                      birthDate:
                        type: string
                        format: date-time
                      birthPlace:
                        type: string
                      fullName:
                        type: string
                      preferredName:
                        type: string
        "400":
          description: Invalid member. Field `memberKey` is not valid, check again with member.
  /story/{mid}:
    post:
      x-openai-isConsequential: false
      operationId: MyLifeBiographerStoryCreation
      summary: MyLife Biographer Bot will access this endpoint to generate a `bio-story` document in MyLife Cosmos.
      description: Endpoint for handling incoming registration webhook data from the MyLife GPT service.
      parameters:
        - name: mid
          in: path
          required: true
          description: The `memberKey` data to be sent by MyLife Biographer Bot. Visitor enters memberKey and it is kept in GPT memory and sent with each request so that MyLife knows partition.
          schema:
            maxLength: 256
            minLength: 40
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              description: The `story` data sent by MyLife Biographer Bot.
              type: object
              required:
                - keywords
                - phaseOfLife
                - summary
                - title
              properties:
                keywords:
                  description: MyLife Biographer Bot interprets (or asks) keywords for this `story`. Should not include relations or names, but would tag content dynamically. Each should be a single word or short phrase.
                  items:
                    description: A single word or short phrase to tag `story` content.
                    maxLength: 64
                    type: string
                  maxItems: 12
                  minItems: 3
                  type: array
                phaseOfLife:
                  description: MyLife Biographer Bot interprets (or asks) phase of life for this `story`. Can be `unkown`.
                  enum:
                    - birth
                    - childhood
                    - adolescence
                    - teenage
                    - young-adult
                    - adulthood
                    - middle-age
                    - senior
                    - end-of-life
                    - past-life
                    - unknown
                    - other
                  type: string
                relationships:
                  description: MyLife Biographer Bot does its best to record individuals (or pets) mentioned in this `story`.
                  items:
                    description: A name of relational individual/pet to the `story` content.
                    type: string
                  maxItems: 24
                  type: array
                summary:
                  description: MyLife Biographer Bot summary of identified `story`.
                  maxLength: 20480
                  type: string
                title:
                  description: MyLife Biographer Bot determines title for this `story`.
                  maxLength: 256
                  type: string
responses:
  "200":
    description: Story submitted successfully.
    content:
      application/json:
        schema:
          type: object
          properties:
            success:
              type: boolean
              const: true
              example: true
            message:
              type: string
              example: Story submitted successfully.
  "400":
    description: No story summary provided. Use `summary` field.
    content:
      application/json:
        schema:
          type: object
          properties:
            success:
              type: boolean
              const: false
              example: false
            message:
              type: string
              example: No story summary provided. Use `summary` field.